#!/bin/sh
OUTPUTS="$(swaymsg -p -t get_outputs)"

function get_interface() {
  echo "${OUTPUTS}" | grep -E '^Output .*'"${1}"'.*$' | sed -E 's/^Output ([^ ]+) .*$/\1/'
}

WIDESCREEN="$(get_interface "Goldstar Company Ltd LG HDR WQHD 0x00008B4F")"
LAPTOP="$(get_interface "Unknown 0x06DF 0x00000000")"
AUX="$(get_interface "Dell Inc. DELL P2214H KW14V52A24DB")"

echo "Configuring aux display (${AUX})"
sway output "${AUX}" mode 1920x1080 pos $((3440 - 200)) 0

echo "Configuring widescreen display (${WIDESCREEN})"
sway output "${WIDESCREEN}" mode 3440x1440 pos 0 1080

echo "Configuring laptop display ("${LAPTOP}")"
sway output "${LAPTOP}" mode 1920x1080 pos 3440 1080

echo "Setting background color"
sway output "*" background '#80a9ed' solid_color

echo "Restarting pulseaudio to detect monitor outputs"
pulseaudio -k

